baseURL = 'https://zacgarby.co.uk/'
languageCode = 'en-us'
title = 'Zac Garby'
theme = 'zacs-blog'

[markup.goldmark.renderer]
unsafe= true

[menu]
    [[menu.main]]
        name = "Zac Garby"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Hackathons"
        url = "/hackathons"
        weight = 2
    
    [[menu.main]]
        name = "Publications"
        url = "/posts"
        weight = 3
    
    [[menu.main]]
        name = "CV"
        url = "/files/cv.pdf"
        weight = 4
    