baseURL = 'https://zacgarby.co.uk/'
languageCode = 'en-us'
title = 'Zac Garby'
theme = 'zacs-blog'

[markup.goldmark.renderer]
unsafe= true

[menu]
    [[menu.main]]
        name = "Zac Garby"
        url = "/"
        weight = 1
        [menu.main.params]
            icon = "/images/nav/zac.png"

    [[menu.main]]
        name = "Hackathons"
        url = "/hackathons"
        weight = 2
        [menu.main.params]
            icon = "/images/nav/hack.png"

    [[menu.main]]
        name = "Publications"
        url = "/posts"
        weight = 3
        [menu.main.params]
            icon = "/images/nav/writing.png"

    [[menu.main]]
        name = "CV"
        url = "/files/cv.pdf"
        weight = 4
        [menu.main.params]
            icon = "/images/nav/cv.png"
